name: Build and deploy Node.js app to Azure Web App - aps-OMU-01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aps-OMU-01'
          slot-name: 'Production'
          package: '.'   # リポジトリのルート（コード一式）をそのまま渡す
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2C6C767FEEAD45CA9BAD0CA08B91C5FB }}
